import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'NovaPhone X1',
    description: 'The latest and greatest smartphone from Nova. Unparalleled performance and a stunning display.',
    price: 999,
    category: 'Smartphones',
    brand: 'Nova',
    stock: 50,
    imageIds: ['product-smartphone-1', 'product-smartphone-2'],
    isFeatured: true,
    newArrival: true,
    rating: 5,
  },
  {
    id: '2',
    name: 'ElectroBook Pro',
    description: 'A professional-grade laptop for all your creative and productive needs. Powerful, sleek, and reliable.',
    price: 1499,
    category: 'Laptops',
    brand: 'Electro',
    stock: 30,
    imageIds: ['product-laptop-1', 'product-laptop-2'],
    isFeatured: true,
    newArrival: false,
    rating: 5,
  },
  {
    id: '3',
    name: 'SonicWave Buds',
    description: 'Immerse yourself in high-fidelity audio with these true wireless earbuds. Crystal clear sound and a comfortable fit.',
    price: 199,
    category: 'Audio',
    brand: 'Sonic',
    stock: 100,
    imageIds: ['product-headphones-1', 'product-headphones-2'],
    isFeatured: false,
    newArrival: true,
    rating: 4,
  },
  {
    id: '4',
    name: 'ConnectWatch 2',
    description: 'Stay connected and track your fitness with the next generation of smartwatches. Stylish and functional.',
    price: 299,
    category: 'Wearables',
    brand: 'Connect',
    stock: 75,
    imageIds: ['product-smartwatch-1', 'product-smartwatch-2'],
    isFeatured: true,
    newArrival: false,
    rating: 4,
  },
  {
    id: '5',
    name: 'NovaShot Camera',
    description: 'Capture life\'s moments in stunning detail with this professional DSLR camera.',
    price: 1999,
    category: 'Cameras',
    brand: 'Nova',
    stock: 20,
    imageIds: ['product-camera-1', 'product-camera-2'],
    isFeatured: false,
    newArrival: false,
    rating: 5,
  },
  {
    id: '6',
    name: 'ElectroDrone Sky',
    description: 'Explore the world from a new perspective with our easy-to-fly 4K drone.',
    price: 799,
    category: 'Drones',
    brand: 'Electro',
    stock: 25,
    imageIds: ['product-drone-1', 'product-drone-2'],
    isFeatured: false,
    newArrival: true,
    rating: 4,
  },
  {
    id: '7',
    name: 'NovaPhone SE',
    description: 'The power of NovaPhone in a more compact and affordable package. Perfect for everyone.',
    price: 499,
    category: 'Smartphones',
    brand: 'Nova',
    stock: 80,
    imageIds: ['product-smartphone-2', 'product-smartphone-1'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '8',
    name: 'ElectroBook Air',
    description: 'Ultra-light, ultra-thin, and ultra-powerful. The perfect laptop for those on the go.',
    price: 1199,
    category: 'Laptops',
    brand: 'Electro',
    stock: 45,
    imageIds: ['product-laptop-2', 'product-laptop-1'],
    isFeatured: false,
    newArrival: true,
    rating: 5,
  },
  {
    id: '9',
    name: 'SonicWave Max',
    description: 'Over-ear headphones with industry-leading noise cancellation and spatial audio.',
    price: 349,
    category: 'Audio',
    brand: 'Sonic',
    stock: 60,
    imageIds: ['product-headphones-2', 'product-headphones-1'],
    isFeatured: true,
    newArrival: false,
    rating: 5,
  },
  {
    id: '10',
    name: 'ConnectBand Fit',
    description: 'A lightweight fitness tracker to monitor your daily activity and sleep patterns.',
    price: 79,
    category: 'Wearables',
    brand: 'Connect',
    stock: 150,
    imageIds: ['product-smartwatch-2', 'product-smartwatch-1'],
    isFeatured: false,
    newArrival: true,
    rating: 4,
  },
  {
    id: '11',
    name: 'NovaTab Pro',
    description: 'A versatile tablet with a stunning Liquid Retina display, perfect for work and play.',
    price: 799,
    category: 'Laptops',
    brand: 'Nova',
    stock: 40,
    imageIds: ['product-laptop-1', 'product-laptops-2'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '12',
    name: 'ElectroCam 360',
    description: 'Capture your world in immersive 360-degree video and photos.',
    price: 499,
    category: 'Cameras',
    brand: 'Electro',
    stock: 35,
    imageIds: ['product-camera-2', 'product-camera-1'],
    isFeatured: false,
    newArrival: true,
    rating: 4,
  },
  {
    id: '13',
    name: 'SonicSoundbar+',
    description: 'Experience cinematic sound in your living room with this Dolby Atmos soundbar.',
    price: 499,
    category: 'Audio',
    brand: 'Sonic',
    stock: 55,
    imageIds: ['product-audio-1', 'product-audio-2'],
    isFeatured: false,
    newArrival: false,
    rating: 5,
  },
  {
    id: '14',
    name: 'ConnectScale',
    description: 'A smart scale that measures weight, body fat, and more, syncing to your ConnectFit app.',
    price: 99,
    category: 'Wearables',
    brand: 'Connect',
    stock: 120,
    imageIds: ['category-wearables', 'product-smartwatch-1'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '15',
    name: 'NovaCam Mini',
    description: 'A compact, high-performance action camera for all your adventures.',
    price: 399,
    category: 'Cameras',
    brand: 'Nova',
    stock: 65,
    imageIds: ['product-camera-1', 'product-camera-2'],
    isFeatured: true,
    newArrival: true,
    rating: 4,
  },
  {
    id: '16',
    name: 'ElectroDrone Pro',
    description: 'A professional drone with a Hasselblad camera for breathtaking aerial photography.',
    price: 1599,
    category: 'Drones',
    brand: 'Electro',
    stock: 15,
    imageIds: ['product-drone-2', 'product-drone-1'],
    isFeatured: true,
    newArrival: false,
    rating: 5,
  },
  {
    id: '17',
    name: 'NovaPhone Ultra',
    description: 'The pinnacle of smartphone technology, featuring a 200MP camera and satellite connectivity.',
    price: 1299,
    category: 'Smartphones',
    brand: 'Nova',
    stock: 25,
    imageIds: ['product-smartphone-1', 'product-smartphone-2'],
    isFeatured: false,
    newArrival: false,
    rating: 5,
  },
  {
    id: '18',
    name: 'ElectroBook Flex',
    description: 'A 2-in-1 convertible laptop with a 360-degree hinge and touchscreen.',
    price: 1399,
    category: 'Laptops',
    brand: 'Electro',
    stock: 30,
    imageIds: ['product-laptops-1', 'product-laptops-2'],
    isFeatured: false,
    newArrival: true,
    rating: 4,
  },
  {
    id: '19',
    name: 'SonicBoom Speaker',
    description: 'A portable, waterproof Bluetooth speaker with powerful bass and a 24-hour battery life.',
    price: 149,
    category: 'Audio',
    brand: 'Sonic',
    stock: 90,
    imageIds: ['product-audio-2', 'product-audio-1'],
    isFeatured: false,
    newArrival: false,
    rating: 5,
  },
  {
    id: '20',
    name: 'ConnectRing',
    description: 'A smart ring that tracks your activity, sleep, and readiness, all in a sleek, minimalist design.',
    price: 299,
    category: 'Wearables',
    brand: 'Connect',
    stock: 50,
    imageIds: ['product-smartwatch-1', 'product-smartwatch-2'],
    isFeatured: false,
    newArrival: true,
    rating: 4,
  },
  {
    id: '21',
    name: 'NovaWebcam 4K',
    description: 'A professional 4K webcam with AI-powered framing and crystal-clear audio.',
    price: 199,
    category: 'Cameras',
    brand: 'Nova',
    stock: 70,
    imageIds: ['product-camera-1', 'product-camera-2'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '22',
    name: 'ElectroDrone Mini',
    description: 'A palm-sized drone that\'s easy to fly and perfect for beginners.',
    price: 399,
    category: 'Drones',
    brand: 'Electro',
    stock: 100,
    imageIds: ['product-drone-1', 'product-drone-2'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '23',
    name: 'NovaBuds Air',
    description: 'Lightweight and comfortable earbuds with adaptive EQ and a magical setup experience.',
    price: 179,
    category: 'Audio',
    brand: 'Nova',
    stock: 85,
    imageIds: ['product-headphones-1', 'product-headphones-2'],
    isFeatured: false,
    newArrival: true,
    rating: 4,
  },
  {
    id: '24',
    name: 'ConnectWatch SE',
    description: 'All the essentials of a smartwatch in a more affordable package. Stay active and connected.',
    price: 199,
    category: 'Wearables',
    brand: 'Connect',
    stock: 95,
    imageIds: ['product-smartwatch-1', 'product-smartwatch-2'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '25',
    name: 'ElectroWorkstation Z8',
    description: 'A powerhouse desktop computer for the most demanding professional workflows.',
    price: 3999,
    category: 'Laptops',
    brand: 'Electro',
    stock: 10,
    imageIds: ['product-laptops-1', 'product-laptops-2'],
    isFeatured: false,
    newArrival: false,
    rating: 5,
  },
  {
    id: '26',
    name: 'SonicMic Pro',
    description: 'A studio-quality USB microphone for podcasting, streaming, and recording music.',
    price: 129,
    category: 'Audio',
    brand: 'Sonic',
    stock: 75,
    imageIds: ['product-audio-1', 'product-audio-2'],
    isFeatured: false,
    newArrival: true,
    rating: 5,
  },
  {
    id: '27',
    name: 'NovaPhone Lite',
    description: 'A budget-friendly smartphone that doesn\'t compromise on quality or performance.',
    price: 299,
    category: 'Smartphones',
    brand: 'Nova',
    stock: 110,
    imageIds: ['product-smartphone-1', 'product-smartphone-2'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '28',
    name: 'ElectroView 5K',
    description: 'A stunning 27-inch 5K monitor with incredible color accuracy and brightness.',
    price: 1299,
    category: 'Laptops',
    brand: 'Electro',
    stock: 20,
    imageIds: ['category-laptops', 'product-laptops-1'],
    isFeatured: false,
    newArrival: false,
    rating: 5,
  },
  {
    id: '29',
    name: 'SonicSport Buds',
    description: 'Sweat and water-resistant earbuds designed to stay in place during your toughest workouts.',
    price: 129,
    category: 'Audio',
    brand: 'Sonic',
    stock: 80,
    imageIds: ['product-headphones-1', 'product-headphones-2'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '30',
    name: 'ConnectGlasses',
    description: 'Smart glasses that bring information and entertainment into your line of sight.',
    price: 599,
    category: 'Wearables',
    brand: 'Connect',
    stock: 25,
    imageIds: ['category-wearables', 'product-smartwatch-1'],
    isFeatured: false,
    newArrival: true,
    rating: 4,
  },
  {
    id: '31',
    name: 'NovaCam Pro',
    description: 'A full-frame mirrorless camera with advanced autofocus and 8K video recording.',
    price: 3499,
    category: 'Cameras',
    brand: 'Nova',
    stock: 12,
    imageIds: ['product-camera-1', 'product-camera-2'],
    isFeatured: false,
    newArrival: false,
    rating: 5,
  },
  {
    id: '32',
    name: 'ElectroDrone Racer',
    description: 'A high-speed FPV racing drone for adrenaline junkies.',
    price: 499,
    category: 'Drones',
    brand: 'Electro',
    stock: 40,
    imageIds: ['product-drone-1', 'product-drone-2'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '33',
    name: 'NovaDock',
    description: 'A powerful docking station to connect all your peripherals to your ElectroBook with a single cable.',
    price: 199,
    category: 'Laptops',
    brand: 'Nova',
    stock: 60,
    imageIds: ['category-laptops', 'product-laptops-1'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '34',
    name: 'SonicHome Max',
    description: 'A smart home hub and speaker with room-filling sound and voice control.',
    price: 299,
    category: 'Audio',
    brand: 'Sonic',
    stock: 45,
    imageIds: ['product-audio-1', 'product-audio-2'],
    isFeatured: false,
    newArrival: true,
    rating: 4,
  },
  {
    id: '35',
    name: 'NovaPhone Fold',
    description: 'A revolutionary folding smartphone that opens up to a large, immersive display.',
    price: 1799,
    category: 'Smartphones',
    brand: 'Nova',
    stock: 18,
    imageIds: ['product-smartphone-1', 'product-smartphone-2'],
    isFeatured: true,
    newArrival: false,
    rating: 5,
  },
  {
    id: '36',
    name: 'ConnectBand Lux',
    description: 'A stylish and luxurious fitness tracker with a leather strap and gold accents.',
    price: 149,
    category: 'Wearables',
    brand: 'Connect',
    stock: 50,
    imageIds: ['product-smartwatch-1', 'product-smartwatch-2'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '37',
    name: 'ElectroPen Pro',
    description: 'A smart stylus for your ElectroBook Flex and NovaTab, offering precise control and low latency.',
    price: 99,
    category: 'Laptops',
    brand: 'Electro',
    stock: 100,
    imageIds: ['category-laptops', 'product-laptops-1'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '38',
    name: 'NovaCam 3D',
    description: 'A 3D camera that captures depth and creates immersive, lifelike images.',
    price: 699,
    category: 'Cameras',
    brand: 'Nova',
    stock: 30,
    imageIds: ['product-camera-1', 'product-camera-2'],
    isFeatured: false,
    newArrival: true,
    rating: 4,
  },
  {
    id: '39',
    name: 'SonicWave Go',
    description: 'A compact and portable speaker with surprising power and a carabiner clip for on-the-go music.',
    price: 59,
    category: 'Audio',
    brand: 'Sonic',
    stock: 120,
    imageIds: ['product-audio-1', 'product-audio-2'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '40',
    name: 'ConnectWatch Ultra',
    description: 'A rugged and capable smartwatch for extreme sports and outdoor adventures.',
    price: 799,
    category: 'Wearables',
    brand: 'Connect',
    stock: 25,
    imageIds: ['product-smartwatch-1', 'product-smartwatch-2'],
    isFeatured: true,
    newArrival: false,
    rating: 5,
  },
  {
    id: '41',
    name: 'ElectroDrone Agri',
    description: 'An agricultural drone for crop spraying and monitoring, improving efficiency and yield.',
    price: 4999,
    category: 'Drones',
    brand: 'Electro',
    stock: 10,
    imageIds: ['product-drone-1', 'product-drone-2'],
    isFeatured: false,
    newArrival: false,
    rating: 5,
  },
  {
    id: '42',
    name: 'NovaPhone Basic',
    description: 'A simple and reliable feature phone for calls and texts, with a long-lasting battery.',
    price: 99,
    category: 'Smartphones',
    brand: 'Nova',
    stock: 200,
    imageIds: ['product-smartphone-1', 'product-smartphone-2'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '43',
    name: 'ElectroPad',
    description: 'A powerful graphics tablet for digital artists and designers.',
    price: 349,
    category: 'Laptops',
    brand: 'Electro',
    stock: 45,
    imageIds: ['category-laptops', 'product-laptops-1'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '44',
    name: 'SonicCast',
    description: 'An audio streaming device that connects to your existing stereo system.',
    price: 49,
    category: 'Audio',
    brand: 'Sonic',
    stock: 150,
    imageIds: ['product-audio-1', 'product-audio-2'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '45',
    name: 'ConnectTag',
    description: 'A small tracker to help you find your keys, wallet, or anything else you can\'t afford to lose.',
    price: 29,
    category: 'Wearables',
    brand: 'Connect',
    stock: 300,
    imageIds: ['category-wearables', 'product-smartwatch-1'],
    isFeatured: false,
    newArrival: true,
    rating: 4,
  },
  {
    id: '46',
    name: 'NovaCam Astro',
    description: 'A specialized camera for astrophotography, with a cooled sensor for long-exposure shots.',
    price: 2999,
    category: 'Cameras',
    brand: 'Nova',
    stock: 15,
    imageIds: ['product-camera-1', 'product-camera-2'],
    isFeatured: false,
    newArrival: false,
    rating: 5,
  },
  {
    id: '47',
    name: 'ElectroDrone Cargo',
    description: 'A heavy-lift drone designed for delivering packages and other cargo.',
    price: 9999,
    category: 'Drones',
    brand: 'Electro',
    stock: 5,
    imageIds: ['product-drone-1', 'product-drone-2'],
    isFeatured: false,
    newArrival: false,
    rating: 5,
  },
  {
    id: '48',
    name: 'NovaHub',
    description: 'A smart display that combines a speaker, screen, and voice assistant for your home.',
    price: 229,
    category: 'Audio',
    brand: 'Nova',
    stock: 60,
    imageIds: ['product-audio-1', 'product-audio-2'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '49',
    name: 'ElectroGamer X',
    description: 'A high-performance gaming laptop with a mechanical keyboard and RGB lighting.',
    price: 2499,
    category: 'Laptops',
    brand: 'Electro',
    stock: 25,
    imageIds: ['product-laptops-1', 'product-laptops-2'],
    isFeatured: true,
    newArrival: true,
    rating: 5,
  },
  {
    id: '50',
    name: 'SonicWave Mini',
    description: 'A pocket-sized Bluetooth speaker that delivers surprisingly big sound.',
    price: 39,
    category: 'Audio',
    brand: 'Sonic',
    stock: 200,
    imageIds: ['product-audio-1', 'product-audio-2'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
];
