import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'NovaPhone X1',
    description: 'The latest and greatest smartphone from Nova. Unparalleled performance and a stunning display.',
    price: 999,
    category: 'Smartphones',
    brand: 'Nova',
    stock: 50,
    imageIds: ['product-smartphone-1', 'product-smartphone-2'],
    isFeatured: true,
    newArrival: true,
    rating: 5,
  },
  {
    id: '2',
    name: 'ElectroBook Pro',
    description: 'A professional-grade laptop for all your creative and productive needs. Powerful, sleek, and reliable.',
    price: 1499,
    category: 'Laptops',
    brand: 'Electro',
    stock: 30,
    imageIds: ['product-laptop-1', 'product-laptop-2'],
    isFeatured: true,
    newArrival: false,
    rating: 5,
  },
  {
    id: '3',
    name: 'SonicWave Buds',
    description: 'Immerse yourself in high-fidelity audio with these true wireless earbuds. Crystal clear sound and a comfortable fit.',
    price: 199,
    category: 'Audio',
    brand: 'Sonic',
    stock: 100,
    imageIds: ['product-headphones-1', 'product-headphones-2'],
    isFeatured: false,
    newArrival: true,
    rating: 4,
  },
  {
    id: '4',
    name: 'ConnectWatch 2',
    description: 'Stay connected and track your fitness with the next generation of smartwatches. Stylish and functional.',
    price: 299,
    category: 'Wearables',
    brand: 'Connect',
    stock: 75,
    imageIds: ['product-smartwatch-1', 'product-smartwatch-2'],
    isFeatured: true,
    newArrival: false,
    rating: 4,
  },
  {
    id: '5',
    name: 'NovaShot Camera',
    description: 'Capture life\'s moments in stunning detail with this professional DSLR camera.',
    price: 1999,
    category: 'Cameras',
    brand: 'Nova',
    stock: 20,
    imageIds: ['product-camera-1', 'product-camera-2'],
    isFeatured: false,
    newArrival: false,
    rating: 5,
  },
  {
    id: '6',
    name: 'ElectroDrone Sky',
    description: 'Explore the world from a new perspective with our easy-to-fly 4K drone.',
    price: 799,
    category: 'Drones',
    brand: 'Electro',
    stock: 25,
    imageIds: ['product-drone-1', 'product-drone-2'],
    isFeatured: false,
    newArrival: true,
    rating: 4,
  },
    {
    id: '7',
    name: 'NovaPhone SE',
    description: 'The power of NovaPhone in a more compact and affordable package. Perfect for everyone.',
    price: 499,
    category: 'Smartphones',
    brand: 'Nova',
    stock: 80,
    imageIds: ['product-smartphone-2', 'product-smartphone-1'],
    isFeatured: false,
    newArrival: false,
    rating: 4,
  },
  {
    id: '8',
    name: 'ElectroBook Air',
    description: 'Ultra-light, ultra-thin, and ultra-powerful. The perfect laptop for those on the go.',
    price: 1199,
    category: 'Laptops',
    brand: 'Electro',
    stock: 45,
    imageIds: ['product-laptop-2', 'product-laptop-1'],
    isFeatured: false,
    newArrival: true,
    rating: 5,
  },
];
